// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Octans.Data.Models;

#nullable disable

namespace Octans.Server.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260514120000_AddHashMediaMetadata")]
    partial class AddHashMediaMetadata
    {
    }
}
