// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Octans.Core.Models;

#nullable disable

namespace Octans.Server.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Octans.Core.Downloaders.DownloadStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrentSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DownloadStatuses");
                });

            modelBuilder.Entity("Octans.Core.Downloaders.QueuedDownload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QueuedDownloads");
                });

            modelBuilder.Entity("Octans.Core.Importing.Jobs.ImportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.ToTable("ImportItems");
                });

            modelBuilder.Entity("Octans.Core.Importing.Jobs.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedRequest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("Octans.Core.Models.Duplicates.DuplicateCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int>("HashId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HashId2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HashId1");

                    b.HasIndex("HashId2");

                    b.ToTable("DuplicateCandidates");
                });

            modelBuilder.Entity("Octans.Core.Models.Duplicates.DuplicateDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HashId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HashId2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resolution")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HashId1");

                    b.HasIndex("HashId2");

                    b.ToTable("DuplicateDecisions");
                });

            modelBuilder.Entity("Octans.Core.Models.FileRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileRecords");
                });

            modelBuilder.Entity("Octans.Core.Models.HashItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ulong?>("PerceptualHash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Hashes");
                });

            modelBuilder.Entity("Octans.Core.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HashItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HashItemId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Octans.Core.Models.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Octans.Core.Models.Ratings.HashRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HashId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HashId");

                    b.HasIndex("RatingSystemId");

                    b.ToTable("HashRatings");
                });

            modelBuilder.Entity("Octans.Core.Models.Ratings.RatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RatingSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxValue = 1,
                            Name = "Favourites",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            MaxValue = 5,
                            Name = "Quality",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Octans.Core.Models.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Repositories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Inbox"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Archive"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trash"
                        });
                });

            modelBuilder.Entity("Octans.Core.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("CheckPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextCheck")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Octans.Core.Models.SubscriptionExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionExecutions");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.Mapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HashId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HashId");

                    b.HasIndex("TagId");

                    b.ToTable("Mappings");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.Namespace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Namespaces");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.Subtag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subtags");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NamespaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubtagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NamespaceId");

                    b.HasIndex("SubtagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.TagParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.ToTable("TagParents");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.TagSibling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdealId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NonIdealId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdealId");

                    b.HasIndex("NonIdealId");

                    b.ToTable("TagSiblings");
                });

            modelBuilder.Entity("Octans.Core.Importing.Jobs.ImportItem", b =>
                {
                    b.HasOne("Octans.Core.Importing.Jobs.ImportJob", "ImportJob")
                        .WithMany("Items")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("Octans.Core.Models.Duplicates.DuplicateCandidate", b =>
                {
                    b.HasOne("Octans.Core.Models.HashItem", "Hash1")
                        .WithMany()
                        .HasForeignKey("HashId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octans.Core.Models.HashItem", "Hash2")
                        .WithMany()
                        .HasForeignKey("HashId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hash1");

                    b.Navigation("Hash2");
                });

            modelBuilder.Entity("Octans.Core.Models.Duplicates.DuplicateDecision", b =>
                {
                    b.HasOne("Octans.Core.Models.HashItem", "Hash1")
                        .WithMany()
                        .HasForeignKey("HashId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octans.Core.Models.HashItem", "Hash2")
                        .WithMany()
                        .HasForeignKey("HashId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hash1");

                    b.Navigation("Hash2");
                });

            modelBuilder.Entity("Octans.Core.Models.HashItem", b =>
                {
                    b.HasOne("Octans.Core.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Octans.Core.Models.Note", b =>
                {
                    b.HasOne("Octans.Core.Models.HashItem", "HashItem")
                        .WithMany("Notes")
                        .HasForeignKey("HashItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HashItem");
                });

            modelBuilder.Entity("Octans.Core.Models.Ratings.HashRating", b =>
                {
                    b.HasOne("Octans.Core.Models.HashItem", "Hash")
                        .WithMany("Ratings")
                        .HasForeignKey("HashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octans.Core.Models.Ratings.RatingSystem", "RatingSystem")
                        .WithMany("HashRatings")
                        .HasForeignKey("RatingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hash");

                    b.Navigation("RatingSystem");
                });

            modelBuilder.Entity("Octans.Core.Models.Subscription", b =>
                {
                    b.HasOne("Octans.Core.Models.Provider", "Provider")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Octans.Core.Models.SubscriptionExecution", b =>
                {
                    b.HasOne("Octans.Core.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.Mapping", b =>
                {
                    b.HasOne("Octans.Core.Models.HashItem", "Hash")
                        .WithMany()
                        .HasForeignKey("HashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octans.Core.Models.Tagging.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hash");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.Tag", b =>
                {
                    b.HasOne("Octans.Core.Models.Tagging.Namespace", "Namespace")
                        .WithMany()
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octans.Core.Models.Tagging.Subtag", "Subtag")
                        .WithMany()
                        .HasForeignKey("SubtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Namespace");

                    b.Navigation("Subtag");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.TagParent", b =>
                {
                    b.HasOne("Octans.Core.Models.Tagging.Tag", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octans.Core.Models.Tagging.Tag", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Octans.Core.Models.Tagging.TagSibling", b =>
                {
                    b.HasOne("Octans.Core.Models.Tagging.Tag", "Ideal")
                        .WithMany()
                        .HasForeignKey("IdealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octans.Core.Models.Tagging.Tag", "NonIdeal")
                        .WithMany()
                        .HasForeignKey("NonIdealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ideal");

                    b.Navigation("NonIdeal");
                });

            modelBuilder.Entity("Octans.Core.Importing.Jobs.ImportJob", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Octans.Core.Models.HashItem", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Octans.Core.Models.Provider", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Octans.Core.Models.Ratings.RatingSystem", b =>
                {
                    b.Navigation("HashRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
