@HydrusReplacement.Server_HostAddress = http://localhost:5185
@DefaultFile = https://i.imgur.com/mtbl1cr.jpeg

POST http://{{HydrusReplacement.Server_HostAddress}}/import
Content-Type: application/json

{
  "Items": [
    {
      "Source": "{{DefaultFile}}",
      "Tags": [
        "tag1",
        "tag2",
        "tag3"
      ]
    }
  ],
  "DeleteAfterImport": false
}
