name: Release

on:
  push:
    tags:
      - 'v*'
  
permissions:
  contents: write                     

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Server
      run: dotnet publish Octans.Server/Octans.Server.csproj -c Release -o publish/server
      
    - name: Build Client
      run: dotnet publish Octans.Client/Octans.Client.csproj -c Release -o publish/client
      
    - name: Zip Server
      run: cd publish/server && zip -r ../../octans-server.zip .
      
    - name: Zip Client
      run: cd publish/client && zip -r ../../octans-client.zip .
      
    - name: Extract version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          octans-server.zip
          octans-client.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}